<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="uk-UA" xml:lang="uk-UA"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.207">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Т’юторіал з R для психологів - 2&nbsp; Приступаємо до аналізу</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./summary.html" rel="next">
<link href="./intro.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Приступаємо до аналізу</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Т’юторіал з R для психологів</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Передмова</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Вступ</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./part1.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Приступаємо до аналізу</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./summary.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Висновки</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">References</a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">на цій сторінці</h2>
   
  <ul>
  <li><a href="#етапи-дослідження" id="toc-етапи-дослідження" class="nav-link active" data-scroll-target="#етапи-дослідження"><span class="toc-section-number">2.1</span>  Етапи дослідження</a></li>
  <li><a href="#інсталяція-r" id="toc-інсталяція-r" class="nav-link" data-scroll-target="#інсталяція-r"><span class="toc-section-number">2.2</span>  Інсталяція R</a></li>
  <li><a href="#підготовка-даних" id="toc-підготовка-даних" class="nav-link" data-scroll-target="#підготовка-даних"><span class="toc-section-number">2.3</span>  Підготовка даних</a></li>
  <li><a href="#опис-даних" id="toc-опис-даних" class="nav-link" data-scroll-target="#опис-даних"><span class="toc-section-number">2.4</span>  Опис даних</a></li>
  <li><a href="#статистична-потужність-і-величина-ефекту" id="toc-статистична-потужність-і-величина-ефекту" class="nav-link" data-scroll-target="#статистична-потужність-і-величина-ефекту"><span class="toc-section-number">2.5</span>  Статистична потужність і величина ефекту</a></li>
  <li><a href="#приклад-визначення-обєму-вибірки" id="toc-приклад-визначення-обєму-вибірки" class="nav-link" data-scroll-target="#приклад-визначення-обєму-вибірки"><span class="toc-section-number">2.6</span>  Приклад визначення об’єму вибірки</a></li>
  <li><a href="#якість-даних" id="toc-якість-даних" class="nav-link" data-scroll-target="#якість-даних"><span class="toc-section-number">2.7</span>  Якість даних</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Приступаємо до аналізу</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>Необхідність власне у програмуванні на початкових етапах використання R не виникає, користувачу достатньо розуміти, як підготувати і імпортувати дані, викликати невелику кількість функцій для виконання перетворень змінних, статистичного аналізу і побудови діаграм, виводити табличні і графічні результати аналізу для їх наступного включення у текст статті або звіту. Пізніше на цій основі можна розвивати важливу для сучасних дослідників компетенцію програмування: створення власних функцій або розробки нових методів статистичного аналізу.</p>
<section id="етапи-дослідження" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="етапи-дослідження"><span class="header-section-number">2.1</span> Етапи дослідження</h2>
<p>Зазвичай емпіричне психологічне дослідження розгортається у такій послідовності: 1) Планування дослідження: визначення його дизайну, величини очікуваних ефектів і потрібного об’єму вибірки, підбір або створення якісних інструментів вимірювання психологічних конструктів; 2) Збирання і введення даних у комп’ютер; 3) Імпорт таблиці даних в середовище R; 4) Попередня обробка даних: використання статистичних процедур для перевірки якості даних (наприклад, пошук незвичних спостережень, які можуть негативно позначитися на результатах — так званих «викидів»), обчислення показників надійності для психологічних шкал; 5) Обчислення індексів (інтегральних показників, факторів), перекодування змінних, створення факторів (категоріальних змінних), категоризація неперервних ознак, агрегація даних, зміна структури таблиці даних (перевертання, витягнення по горизонталі чи вертикалі); 6) Відбір спостережень для аналізу (наприклад, виключення пропущених значень чи зосередження на цільовій сукупності досліджуваних); 7) Виклик статистичних процедур для опису даних, перевірки гіпотез і побудови статистичних моделей; 8) Створення фінального звіту за результатами. R за допомогою мови розмітки Markdown дозволяє генерувати такі звіти з таблицями, графіками і довільним текстом у форматі PDF, HTML і Word.</p>
</section>
<section id="інсталяція-r" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="інсталяція-r"><span class="header-section-number">2.2</span> Інсталяція R</h2>
<p>Перед початком роботи потрібно встановити R на комп’ютері з дистрибутивів в залежності від типу операційної системи (див. веб-сайт проекту https://cran.r-project.org/ або компанії Майкрософт https://mran.microsoft.com/). Набагато зручніше працювати з R у спеціальному середовищі розробника — RStudio (див. https://rstudio.com/). Проте для початківців найкращий варіант — скористатися хмарною версією R і RStudio, яку можна знайти за посиланням http://rstudio.cloud. Вхід до хмарної версії здійснюється після простої процедури реєстрації. Суттєвими перевагами цього способу є відсутність необхідності інсталювати і оновлювати програми на власному комп’ютері, постійний доступ до даних і скриптів аналізу через мережу Інтернет, а також можливість спільної роботи з викладачем чи іншими дослідниками.</p>
</section>
<section id="підготовка-даних" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="підготовка-даних"><span class="header-section-number">2.3</span> Підготовка даних</h2>
<p>Найбільш оптимальним форматом збереження даних для початківця є формат Microsoft Excel. Якщо цей табличний процесор не встановлений на вашому комп’ютері, можна скористатися безплатним сервісом Google Таблиці. Це особливо зручно, коли збирання даних здійснюється за допомогою сервісу опитувань Google Форми, оскільки відповіді респондентів відразу зберігаються у потрібному вигляді. Зібрані дані можна звантажити у форматі Microsoft Excel, або скористатися можливістю отримати доступ до них безпосередньо з R.</p>
</section>
<section id="опис-даних" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="опис-даних"><span class="header-section-number">2.4</span> Опис даних</h2>
<p>Дані, на яких будуть демонструватися можливості R в цій статті, представляють собою результати опитування студентів НаУКМА, проведеного у 2019 році в рамках бакалаврської кваліфікаційної роботи Марією Жаб’юк за адаптованою версією шкали Perceived Stress Scale (Cohen et al., 1983).</p>
<p>Шкала PSS складається з 10 питань, мета яких – отримати інформацію про те, в якій мірі досліджувані сприймають різноманітні обставини свого життя як стресові.</p>
<p>Наприклад, перше питання має такий вигляд: «Наскільки часто ви за останній місяць … Були засмучені через те, що сталось несподівано?».</p>
<p>Досліджувані обирали один з п’яти варіантів відповіді: ніколи (0 балів), майже ніколи (1 бал), іноді (2 бали), доволі часто (3 бали), дуже часто (4 бали).</p>
<p>Половина пунктів шкали має зворотний ключ (питання 4, 5, 7, 8) для контролю установки давати однакові відповіді.</p>
<p>Picture 1</p>
<p>Таблиця даних містить відповіді 462 досліджуваних (див. Рис. 1). На додаток до ідентифікаційного номеру досліджуваного і десяти питань шкали PSS в ній представлені стать (gender), курс (year) і фінансовий стан сім’ї студента (fin_state).</p>
<p>Переглянути і завантажити ці дані в форматі Excel можна за посиланням https://osf.io/egs3d/ з сайту Open Science Framework (OSF).</p>
<p>На прикладі цієї таблиці легко пояснити основні моменти підготовки даних дослідження для наступного статистичного аналізу в R:</p>
<ol type="1">
<li><p>Перший рядок таблиці має містити імена змінних (їхні скорочені позначення). Правила вибору імен для змінних наступні: вони мають починатися з літери (краще латинського алфавіту) чи крапки, після яких можуть йти інші літери, цифри 0-9, крапка чи символ нижнього підкреслювання. Пробіл в іменах змінних є неприпустимим. Імена варто обирати так, щоб можна було легко зрозуміти, яка змінна аналізується. Зверніть увагу, що R розрізняє великі і маленькі літери в іменах об’єктів, тому змінні gender, Gender і GENDER будуть сприйматися як різні.</p></li>
<li><p>За бажанням розгорнуту інформацію про змінну можна розмістити у додатковому аркуші книги (на Рис. 1 це аркуш Variable View). Загалом функції R, на відміну від пакету IBM SPSS Statistics, не працюють з довгими текстовими мітками змінних (variable label), проте це обмеження при необхідності можна легко обійти.</p></li>
<li><p>Перший стовпчик таблиці має містити унікальний код досліджуваного, за яким його можна ідентифікувати при здійсненні злиття, відбору, чистки даних чи внесенні додаткової інформації про учасників, що може з’явитися пізніше. Важливо зберігати анонімність досліджуваних, якщо дані будуть розповсюджуватися, тому ідентифікувати їх краще за все числами або спеціальними кодами.</p></li>
<li><p>Якщо значення певної змінної у досліджуваного з тих чи інших причин відсутнє, клітинку потрібно лишити пустою. При імпорті даних в R пусті клітинки отримають спеціальне значення NA («Not Available»), яке буде враховуватися при обчисленнях. Також відсутні значення можна закодувати рядком NA або будь-яким числом, яке буде вказуватися при імпорті даних як ознака пропуску. Познайомимося тепер з інтерфейсом програми RStudio (див. Рис. 2). Після входу у хмарну версію користувач потрапляє на сторінку з переліком своїх проектів. Для створення нового проекту треба клацнути кнопку New Project, після чого на екран завантажується застосунок RStudio. Він має рядок меню, панель інструментів і три віконця з вкладками. За замовчанням з лівого боку розташовано вікно консолі, в якому користувач вводить команди і отримує текстові результати виконання команд і повідомлення системи. Цей режим роботи не дуже зручний для початківця, тому варто в якості першого кроку відкрити додаткове вікно для введення тексту майбутнього скрипту (сценарію, програми) аналізу даних. Для цього оберіть в меню застосунку RStudio послідовність команд File – New File – R Script. На Рис. 2 це вікно позначено кружечком з цифрою 1. Поки вміст цього вікна не збережений, його назва Untitled 1.</p></li>
</ol>
<p>Picture 2</p>
<p>У віконці 1 користувач вводить текст сценарію обробки своїх даних, запускає на виконання окремий рядок, блок рядків чи увесь сценарій, а результати виконання команд будуть з’являтися в інших віконцях. Так, у віконці №3 відображається луна виконаних команд і їхні текстові результати, у віконці №2 (вкладка Global Environment, Глобальне Середовище) з’являтимуться створені під час аналізу об’єкти (наприклад, таблиці з імпортованими чи проміжними даними).</p>
<p>Віконце №4 містить найбільшу кількість корисних для початківця вкладок. Тут відображаються файли у поточній папці (вкладка Files), побудовані графіки (вкладка Plots), встановлені пакети (вкладка Packages), довідкова інформація (вкладка Help), згенеровані функціями веб-сторінки (вкладка Viewer).</p>
<p>Для проведення аналізу у хмарній версії RStudio підготовлений файл даних у форматі Excel слід спершу завантажити у хмарне сховище. Для цього у віконці №4 на вкладці Files клацніть кнопку Upload («завантажити»), оберіть файл з даними (наприклад, файл pss.xlsx), який знаходиться на вашому комп’ютері і дайте підтвердження. Після успішного завантаження ім’я файлу з’явиться у переліку файлів вкладки Files.</p>
<p>Наступний крок – імпорт даних з файлу. Цей крок зазвичай здійснюється за допомогою виклику відповідної функції з потрібними аргументами, але для початківця простіше обрати в меню застосунку команду File – Import Dataset – From Excel. Якщо RStudio виведе діалогове вікно з питанням про оновлення необхідних для імпорту пакетів, дайте ствердну відповідь і зачекайте, поки RStudio виконує компіляцію і встановлення пакетів.</p>
<p>Діалогове вікно імпорту файлів Excel має декілька елементів керування. Перш за все знайдіть потрібний файл (в нашому випадку це pss.xlsx), клацнувши кнопку Browse. Попередній перегляд вмісту файлу буде виведене у таблиці Data Preview. В групі опцій імпорту елементи мають таке призначення: поле Name має містити ім’я об’єкту – таблиці даних, в яку після імпорту потрапить вміст файлу. У випадаючому списку Sheets можна обрати ім’я аркушу книги для читання (за замовчанням читатиметься перший аркуш). Оберіть аркуш з назвою «Data View».</p>
<p>Поле NA має містити код, яким ви позначили пропущені дані у файлі. Якщо ви скористалися моєю порадою і пропущені значення кодували за допомогою пустих клітинок в таблиці Excel, це поле можна лишити незаповненим. Нарешті, встановлений прапорець First Row as Names повідомляє процедурі імпорту, що імена майбутніх змінних таблиці даних слід брати з першого рядку файлу Excel. Зверніть увагу на те, що у віконці Code Preview знаходиться декілька рядків команд на мові R, які власне і здійснюють імпортування даних. На їхньому прикладі ви почнете знайомитися з мовою R. Скопіюйте їх у текст вашої першої програми аналізу даних. Я трохи змінив зовнішній вигляд команд для кращої читабельності і додав коментарі (пояснювальний текст, що йде після символу #)– див. Фрагмент коду 1:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Завантаження пакету для імпорту даних в форматі MS Excel</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Імпорт даних з файлу</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>pss <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">path =</span> <span class="st">"pss.xlsx"</span>, <span class="at">sheet =</span> <span class="st">"Data View"</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Виведення вмісту об'єкту на екран</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>pss</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 462 × 14
      id    b1    b2    b3    b4    b5    b6    b7    b8    b9   b10 gender
   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
 1     1     0     0     1     3     3     1     2     3     3     0      1
 2     2     2     1     4     2     1     1     2     0     3     2      2
 3     3     1     2     3     1     1     3     1     1     3     2      2
 4     4     1     2     2     3     3     3     1     1     4     2      2
 5     5     3     3     3     3     3     2     3     2     1     1      2
 6     6     0     1     4     3     4     0     3     3     0     3      1
 7     7     1     4     4     1     0     3     0     1     4     4      1
 8     8     2     1     2     3     2     1     2     2     2     1      1
 9     9     2     2     1     4     3     0     3     3     2     1      1
10    10     2     2     4     3     2     3     2     2     2     3      2
# … with 452 more rows, and 2 more variables: year &lt;dbl&gt;, fin_state &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Розберемо цей фрагмент програми, з якого практично завжди починається аналіз даних. По-перше, слід запам’ятати, що дві представлені в ньому команди <em>library()</em> та <strong>read_excel()</strong> називаються функціями. Функції відіграють надзвичайно важливу роль в R, кожна з них має своє особливе призначення — імпорт чи перетворення даних, побудова діаграм, виконання статистичного аналізу і виведення результатів у потрібному вигляді здійснюється відповідними функціями. Для цього функціям при виклику передається інформація у вигляді аргументів – таблиць даних і змінних у них, а також вказівок на бажаний характер переробки вхідної інформації і виведення результатів (опцій).</p>
<p>Аргументи функції йдуть у послідовному порядку і можуть мати свої власні імена. Наприклад, функція read_excel() має аж дванадцять аргументів, які визначають безліч корисних аспектів її поведінки в різних обставинах (наприклад, назви і типи стовпчиків таблиці даних, кодування пропущених значень тощо). Ми використали два найважливіших аргументи з іменами path (шлях і ім’я файлу Excel, з якого відбувається імпорт даних) і sheet (ім’я аркуша книги). Оскільки ці два аргументи йдуть першими, можна було б і не вказувати їхні імена при виклику функції, але обов’язкове іменування аргументів – корисна практика для початківців, оскільки дозволяє краще розуміти створений скрипт. Зауважте, що в цьому прикладі обом аргументам функції передаються рядкові значення, взяті у подвійні лапки. Знак = («дорівнює») відділяє ім’я аргументу і значення, яке йому передається, а один аргумент від іншого відділяється комою.</p>
<p>Деякі аргументи функції мають значення «за замовчанням», тобто, якщо користувач при виклику функції не вказує цей аргумент, його значення встановлюється автоматично. Наприклад, аргумент <strong>col_names</strong> має логічне значення за замовчанням <strong>TRUE</strong> (істина, тобто – «так, в файлі перший рядок містить імена стовпчиків»). Аргументи за замовчанням має сенс вказувати тільки тоді, коли ви хочете передати їм якесь інше значення.</p>
<p>Виклик функції може давати безпосередній і побічний результат. Функція, як кажуть програмісти, <em>повертає</em> безпосередній результат. В R це може бути вектор, що складається тільки з елементів одного й того ж типу – чисел, рядків тексту або логічних значень (так звані «атомарні вектори»). Функція також може повертати вектор, елементами якого є об’єкти різного типу – вектори, матриці, списки. Такі особливі вектори називаються списками (list). Ви звернули увагу, що елементами списку можуть бути інші списки? Списки дуже корисні для зберігання комплексної інформації і будуть зустрічатися нам весь час при аналізі даних в R – як структура для зберігання даних, аргумент функцій і результат, який функція повертає. Наприклад, функція read_excel() повертає особливий тип списку під назвою tibble, в якому R зберігає таблицю даних емпіричного дослідження.</p>
<p>До речі, не лякайтеся терміну «вектор», для вас зараз це має означати лише послідовність певних значень. Вектори в R відіграють різні ролі – це можуть бути змінні, які піддаються аналізу, опції для функцій, або результати, які повертають функції. Найпростіший спосіб створити вектор чисел (чи рядків, логічних значень тощо) – скористатися особливою функцією <strong>c()</strong>. Їй в дужках передаються через кому аргументи, які функція зчіплює в один об’єкт-вектор. Наприклад, виклик c(1, 2, 3, 4, 5) створить вектор з п’яти цілих чисел від 1 до 5. Існує зручний скорочений спосіб створення таких послідовностей цілих чисел, який ви будете часто використовувати для того, щоб звернутися до послідовних стовпчиків таблиці даних. Запис 1:5, наприклад, згенерує таку саму послідовність з п’яти цілих чисел:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1 2 3 4 5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span><span class="sc">:</span><span class="dv">5</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1 2 3 4 5</code></pre>
</div>
</div>
<p>Результат, який повернула функція, має бути збережений, щоб його можна було використовувати надалі в скрипті. Якщо цього не зробити, він просто друкується на екрані. Для зв’язування об’єкту-результату і обраного аналітиком імені в R є спеціальний оператор присвоєння, який складається з двох символів – знаку «менше» та дефісу – і виглядає, як стрілка. У короткому фрагменті скрипту, який ми розбираємо, за допомогою оператора присвоєння імпортовані з Excel дані записуються в об’єкт на ім’я pss. Цей об’єкт після імпорту і зв’язування з іменем починає існувати у Глобальному Середовищі (на Рис. 2 ви можете побачити його у віконці №2). Тепер до об’єкта pss можна звертатися, передаючи його іншим корисним функціям.</p>
<p>Окрім безпосереднього результату, який функція повертає, вона може бути корисною своїми побічними ефектами. Наприклад, функція hist() в якості побічного результату будує спеціальний графік – гістограму – для переданого їй вектору даних.</p>
<p>Залишилося пояснити перший рядок фрагменту нашої програми. Що означає команда library(readxl)? Справа в тому, що функцій в R величезна кількість. Тому їх групують за призначенням у так звані «пакети» (packages). Частина пакетів є базовими і встановлюються при інсталяції R і RStudio. Необов’язкові пакети (а їх зараз нараховується десятки тисяч) потрібно спочатку встановити із спеціальних сховищ в Інтернеті («репозиторіїв») і підключити до сеансу роботи, щоб функції, які в них включені, стали доступними для виклику. Функція library() якраз і призначена для підключення пакету readxl до сеансу роботи. Як зрозуміло з назви пакету, він містить функції для читання файлів у форматі Microsoft Excel.</p>
<p>Для відтворення процедур аналізу даних, які розглядаються в цій статті, вам необхідно інсталювати з репозиторію такі пакети: readxl, psych, pwr, dplyr, car, jmv, MBESS, MOTE. Кожен з них, в свою чергу, може залежати від інших пакетів, які будуть встановлюватися автоматично. Найпростіший для початківця спосіб інсталяції пакета передбачає використання меню застосунку RStudio. Оберіть в ньому команду Tools – Install Packages і вкажіть назви пакетів у діалоговому вікні, що з’явиться на екрані. Після інсталяції назви нових пакетів будуть додані до списку у бібліотеці користувача (див. вкладку Packages віконця №4).</p>
</section>
<section id="статистична-потужність-і-величина-ефекту" class="level2" data-number="2.5">
<h2 data-number="2.5" class="anchored" data-anchor-id="статистична-потужність-і-величина-ефекту"><span class="header-section-number">2.5</span> Статистична потужність і величина ефекту</h2>
<p>Розібравшись із тим, як в R використовуються функції, ми можемо повернутися до розгляду того, що вібувається на етапі планування дослідження. Одним з важливих чинників кризи відтворюваності часто називають некоректну практику перевірки статистичних гіпотез, у зв’язку з чим західні дослідники неодноразово пропонували вжити ті чи інші заходи – включаючи навіть її повну заборону. Наведу приклад, який висвітлює лише невелику частку проблем, пов’язаних з перевіркою статистичних гіпотез. Припустимо, сто дослідників незалежно один від одного вирішили вивчити, як відрізняються за рівнем академічного інтелекту типові представники двох популяцій – успішних і неуспішних студентів. Нехай середнє значення для першої популяції насправді дорівнює 108 IQ-балів, для другої – 100 IQ-балів, а стандартне відхилення в обох складає 15 IQ-балів. Тобто, різниця середніх двох популяцій дорівнює приблизно половині стандартного відхилення шкали IQ. Зрозуміло, що провести суцільне обстеження популяцій нереально через брак часу і ресурсів, тому зазвичай дослідники вимушені мати справу з вибірками. Якщо випадковим чином обирати вибірки по 25 досліджуваних з кожної популяції (об’єм, який часто рекомендують наукові керівники своїм студентам), то приблизно у половині з ста досліджень різниця середніх на основі t-критерію Ст’юдента не буде визнана статистично значущою на рівні α = 0.05. Причиною такого результату є низька статистична потужність (power) критерію для такого плану дослідження. Потужністю називають ймовірність відкидання нульової гіпотези, коли вона є насправді (тобто, в популяції) невірною. Відомий американський методолог Джейкоб Коен ще у 1962 році провів вивчення статистичної потужності досліджень, опублікованих в журналі Journal of Abnormal and Social Psychology за рік, і показав, що вона дорівнювала 0.48 для тих результатів, що були отримані (Cohen, 1992). Аналогічні показники потужності спостерігалися й у більш сучасних виданнях. Таким чином, якщо об’єм вибірки не сприяв високій ймовірності знайти статистично значущі ефекти, а вони тим не менше були виявлені у дослідженні, тоді, скоріше за все, мали місце сумнівні дослідницькі практики (наприклад, p-hacking – полювання за статистично значущими результатами).</p>
<p>З іншого боку, якщо використовувати надзвичайно великі вибірки, з’являється інша проблема: статистично значущими стають фактично будь-які відмінності чи кореляції, незважаючи на відсутність практично значимих результатів. Це пояснюється тим, що нульова гіпотеза часто формулюється як нереалістичне твердження про те, що в популяції параметр (наприклад, коефіцієнт кореляції, різниця відсотків чи середніх) в точності дорівнює нулю. Оскільки в дійсності це завжди не так, то велика вибірка дозволяє прийняти альтернативну гіпотезу про те, що параметр відрізняється від нуля, хоча ця відмінність може бути цілком тривіальною. Отже, р-значення має поступитися місцем більш релевантним показникам, які дозволяють зробити висновок про величину знайденого в дослідженні ефекту.</p>
<p>Важливість робіт Дж. Коена для поведінкових наук полягає в тому, що він: 1) Створив систему показників величини ефекту для найбільш розповсюджених статистичних критеріїв; 2) Запропонував для кожного показника орієнтовні значення, які відповідають слабкому, посередньому і сильному ефекту; 3) Звернув увагу дослідників на необхідність враховувати потужність і величину ефекту при плануванні дослідження.</p>
<p>Найбільш детально підхід Дж. Коена викладено у другому виданні його відомої монографії, яка присвячена аналізу статистичної потужності (Cohen, 1988). В цьому т’юторіалі я спираюсь на його коротку статтю, в якій наводяться основні результати цієї монографії (Cohen, 1992), щоб продемонструвати роботу з найбільш поширеними в психології базовими статистичними методами для пошуку взаємозалежності двох змінних: 1) Порівняння середніх у двох незалежних сукупностях за допомогою t-критерію Ст’юдента, величина ефекту d Коена; 2) Порівняння середніх у декількох незалежних сукупностях за допомогою однофакторного дисперсійного аналізу, величина ефекту ω^2 (омега в квадраті) і f^2; 3) Характеристика сили і напряму лінійного зв’язку двох неперервних нормально розподілених змінних за допомогою коефіцієнту кореляції Пірсона r; 4) Вивчення сили і характеру зв’язку двох категоріальних змінних за допомогою таблиці сполучення, величина ефекту w Коена.</p>
<p>В таблиці 1 для кожного з згаданих показників наведено значення для слабкого, посереднього і сильного ефекту. Варто зазначити, що такий підхід часто критикують в сучасні літературі (Kline, 2019, с. 180), оскільки кожна з галузей психології може мати свої власні стандарти величини ефекту й вона не обов’язково свідчить про практичну значущість. Проте, така класифікація, на мою думку, є дуже важливою як дидактичний засіб для початківців. Наприклад, часто початківці вважають, що кореляції, менші за 0.5, не заслуговують на увагу, тому обирають такі інструменти і дизайн дослідження, які гарантують отримання сильних, але насправді малоінформативних кореляцій змінних.</p>
<div id="tbl-effects" class="anchored">
<table class="table">
<caption>Table&nbsp;2.1: Показники величини ефекту і їхні рівні</caption>
<thead>
<tr class="header">
<th>Показник</th>
<th style="text-align: right;">Слабкий</th>
<th style="text-align: right;">Посередній</th>
<th style="text-align: right;">Сильний</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(d\)</span></td>
<td style="text-align: right;">0.20</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">0.80</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\omega^2\)</span></td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.06</td>
<td style="text-align: right;">0.14</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(f^2\)</span></td>
<td style="text-align: right;">0.02</td>
<td style="text-align: right;">0.15</td>
<td style="text-align: right;">0.35</td>
</tr>
<tr class="even">
<td><span class="math inline">\(r\)</span></td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">0.30</td>
<td style="text-align: right;">0.50</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(w\)</span></td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">0.30</td>
<td style="text-align: right;">0.50</td>
</tr>
</tbody>
</table>
</div>
<p>Загалом емпіричні дослідження можна розділити на пошукові (експлораторні) і підтверджувальні (конфірматорні). Перші спрямовані на пошук потенційно важливих закономірностей, які можуть лягти в основу нової психологічної теорії. Другі передбачають перевірку і розвиток існуючої теорії. Дуже важливо не плутати ці різні жанри і не видавати пошукові дослідження за підтверджувальні.</p>
<p>Саме при проведенні підтверджувального дослідження важливим кроком є визначення необхідного об’єму вибірки, який забезпечить достатню статистичну потужність для виявлення очікуваної на основі теорії чи попередніх публікацій величини ефекту. В R пакеті pwr містяться функції, які дають можливість виконати обчислення об’єму вибірки за формулами, які запропонував Дж. Коен.</p>
</section>
<section id="приклад-визначення-обєму-вибірки" class="level2" data-number="2.6">
<h2 data-number="2.6" class="anchored" data-anchor-id="приклад-визначення-обєму-вибірки"><span class="header-section-number">2.6</span> Приклад визначення об’єму вибірки</h2>
<p>У дослідженні сприйняття стресу за шкалою PSS (Cohen et al., 1983) на репрезентативній вибірці були отримані наступні дані: Чоловіки – 926 досліджуваних, середнє 12.1, стандартне відхилення 5.9; Жінки – 1406 досліджуваних, середнє 13.7, стандартне відхилення 6.6. На основі цих статистик показник величини ефекту d Коена (стандартизована різниця середніх) склав 0.256. Тобто, жінки переживають більший стрес у порівнянні з чоловіками, проте ця закономірність має слабку вираженість. Припустимо, що подібна різниця середніх буде спостерігатися також для популяції студентів НаУКМА. Яким має бути об’єм вибірок, щоб на рівні значущості α = 0.05 з статистичною потужністю 0.80 для t-критерію Ст’юдента для незалежних сукупностей перевірити альтернативну гіпотезу про вищий рівень стресу у жінок? Отримати відповідь на це питання допоможе наступний код на R, який дасть рішення – 189 спостережень у кожній групі:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pwr)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">pwr.t.test</span>(</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">d =</span> <span class="fl">0.256</span>, <span class="at">power =</span> <span class="fl">0.80</span>, </span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">sig.level =</span> <span class="fl">0.05</span>, <span class="at">type =</span> <span class="st">"two.sample"</span>, <span class="at">alternative =</span> <span class="st">"greater"</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Two-sample t test power calculation 

              n = 189.3567
              d = 0.256
      sig.level = 0.05
          power = 0.8
    alternative = greater

NOTE: n is number in *each* group</code></pre>
</div>
</div>
<p>Аналогічним чином визначається потрібний об’єм вибірки для виявлення слабких ефектів перед проведенням досліджень за допомогою інших трьох критеріїв: однофакторного дисперсійного аналізу з трьома групами (482 спостереження), коефіцієнту кореляції Пірсона (782 спостереження) та критерію w Коена для зв’язку в таблиці сполучення з п’ятьма рядками і двома стовпчиками (1194 спостереження). Аргумент «кількість ступенів свободи» для останнього випадку визначається як df = (кількість рядків – 1)(кількість стовпчиків – 1):</p>
<p>Фрагмент коду 3. Визначення потужності для f², r і w</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pwr.f2.test</span>(<span class="at">u =</span> <span class="dv">3</span> <span class="sc">-</span> <span class="dv">1</span>, <span class="at">f2 =</span> <span class="fl">0.02</span>, <span class="at">sig.level =</span> <span class="fl">0.05</span>, <span class="at">power =</span> <span class="fl">0.80</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Multiple regression power calculation 

              u = 2
              v = 481.7428
             f2 = 0.02
      sig.level = 0.05
          power = 0.8</code></pre>
</div>
</div>
<pre><code>pwr.r.test(r = 0.1, sig.level = 0.05, power = 0.8)

pwr.chisq.test(w = 0.1, df = 4, sig.level = 0.05, power = 0.8)</code></pre>
<p>Згідно сучасних вимог до публікацій, розроблених Американською Психологічною Асоціацією (далі АПА), статті мають містити опис проведеного перед дослідженням аналізу статистичної потужності, а також всіх відхилень від запланованого об’єму вибірок (Publication Manual of the American Psychological Association, 2019).</p>
</section>
<section id="якість-даних" class="level2" data-number="2.7">
<h2 data-number="2.7" class="anchored" data-anchor-id="якість-даних"><span class="header-section-number">2.7</span> Якість даних</h2>
<p>На наступному, четвертому етапі аналізу, здійснюється перевірка якості зібраної інформації – визначення надійності даних, на основі яких обчислюються інтегральні показники (шкали), вивчення розподілу змінних, пошук незвичних спостережень. Легковажне ставлення дослідників до якості психологічного вимірювання є однією з суттєвих причин кризи відтворюваності. В літературі для позначення цієї проблеми використовується термін «сумнівні вимірювальні практики» (Flake &amp; Fried, 2019). Стандарти АПА вимагають надання інформації про надійність і свідчення про валідність вимірювальних інструментів (тестів, спостерігачів, апаратури) на вибірці дослідження. Розповсюджену сьогодні практику наводити показник надійності-узгодженості α (альфа) Кронбаха західні методологи вважають застарілою і не завжди адекватною, оскільки він виходить з припущень про так звану «тау-еквівалентність» пунктів шкали (однакове навантаження на одну латентну змінну) і може мати високе значення, незважаючи на неодномірність даних (тобто, за відповідями можуть стояти декілька навіть не пов’язаних між собою латентних змінних). Більш коректний підхід полягає у перевірці явно заданої вимірювальної моделі засобами конфірматорного факторного аналізу і обчисленні міри надійності на її основі. Ця техніка знаходиться за рамками предмету даного т’юторіалу, тому тут я наведу найпростіший варіант: обчислення такого показника надійності, як ω (омега) МакДональда, на основі припущення про одномірність сукупності індикаторів на прикладі даних 10 питань шкали PSS:</p>
<p>Фрагмент коду 4. Обчислення α Кронбаха і ω МакДональда</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(jmv)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">reliability</span>(</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> pss, <span class="at">vars =</span> <span class="fu">c</span>(b1, b2, b3, b4, b5, b6, b7, b8, b9, b10),</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">revItems =</span> <span class="fu">c</span>(b4, b5, b7, b8),</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">omegaScale =</span> <span class="cn">TRUE</span>, <span class="at">omegaItems =</span> <span class="cn">TRUE</span> </span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 RELIABILITY ANALYSIS

 Scale Reliability Statistics              
 ───────────────────────────────────────── 
            Cronbach's α    McDonald's ω   
 ───────────────────────────────────────── 
   scale       0.8562137       0.8592846   
 ───────────────────────────────────────── 


 Item Reliability Statistics 
 ─────────────────────────── 
            McDonald's ω   
 ─────────────────────────── 
   b1          0.8565352   
   b2          0.8393346   
   b3          0.8436080   
   b4  ᵃ       0.8422876   
   b5  ᵃ       0.8499248   
   b6          0.8520474   
   b7  ᵃ       0.8446754   
   b8  ᵃ       0.8438159   
   b9          0.8501385   
   b10         0.8379350   
 ─────────────────────────── 
   ᵃ reverse scaled item</code></pre>
</div>
</div>
<p>В цьому блоці функції reliability() з пакету jmv передаються такі аргументи: data – таблиця даних pss, в якій містяться відповіді досліджуваних, vars ¬– вектор імен десяти змінних b1-b10, які є індикаторами суб’єктивного стресу, revItems – вектор імен чотирьох змінних з зворотним ключем, omegaScale – опція, яка замовляє виведення показника ω, omegaItems – опція, яка замовляє виведення інформації про надійність шкали за показником ω, коли з неї видалено відповідний індикатор.</p>
<p>На даних нашого дослідження ω дорівнює 0.859, що свідчить про їхню задовільну надійність (має бути вищою за 0.75). Іншими словами, досліджувані цієї вибірки відповідали на питання шкали узгоджено. Часто серед індикаторів шкали можуть траплятися не зовсім якісні пункти (поганий переклад питань, переплутаний напрям ключа, проблеми з розумінням питання саме в цій групі досліджуваних). Отримати інформацію про індикатори, на які варто звернути увагу для покращення якості вимірювання конструкту, можна з наступної таблиці 2:</p>
<p>Таблиця 2. Статистики надійності пунктів шкали</p>
<p>Як можемо бачити, при викиданні жодного питання надійність шкали не збільшується. Без першого питання вона стає рівною 0.856, тобто, загальна надійність при його виключенні практично не зміниться, тому можна було б скоротити шкалу при необхідності. Проте насправді причини такого стану справ можуть бути значно складнішими, так що не варто поспішати.</p>
<p>Переконавшись у тому, що шкали мають прийнятну надійність, можна переходити до створення потрібних нових змінних і перетворення існуючих. Перший тип перетворень – створення категоріальних змінних чи факторів з кількісних. У нашій таблиці даних pss є змінна gender, яка в закодованому вигляді містить інформацію про стать досліджуваного: одиницею позначені чоловіки, двійкою – жінки. Ця змінна має мати номінальну шкалу, оскільки її значення вказують на приналежність досліджуваного до певної категорії. Виконання потрібного перетворення здійснюється за допомогою функції factor():</p>
<p>Фрагмент коду 5. Створення категоріальної змінної – номінального фактору</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>pss<span class="sc">$</span>sex <span class="ot">&lt;-</span> <span class="fu">factor</span>(</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> pss<span class="sc">$</span>gender, </span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), </span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Чоловіки"</span>, <span class="st">"Жінки"</span>)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Аргументами цієї функції є: x – змінна (стовпчик в таблиці даних), яку треба перетворити на фактор. Після знаку = у вищенаведеному фрагменті змінна вказується рядком pss$gender. Тобто, спочатку йде ім’я таблиці даних, потім спеціальний символ-розділювач $ (знак долара), а потім назва стовпчика в таблиці. Мова R має декілька альтернативних способів вказати ім’я однієї змінної: <code>pss[["gender"]]</code> або <code>pss[[12]]</code> – змінна gender розташована в дванадцятому стовпчику таблиці даних і до неї можна звернутися за номером 12. Подвійні квадратні дужки і знак долара використовуються для доступу до елементів списку, а таблиці даних є одним з варіантів списку.</p>
<p>Аргумент levels (рівні фактора) має отримати вектор значень, які може приймати вхідна змінна (в даному випадку це числа 1 і 2). Аргументу labels передається вектор рядків, що відповідають текстовим позначенням рівнів фактору. Створений функцією вектор-фактор присвоюється новому стовпчику таблиці pss з назвою sex. Як бачимо, тут використовується спосіб звертання до змінних в таблиці даних з використанням знаку долара.</p>
<p>Інші важливі перетворення змінних, які часто застосовуються в психологічних дослідженнях, включають в себе: 1) Обчислення інтегральних показників (шкал); 2) Категоризація неперервних змінних; 3) Перекодування одних значень змінної на інші; 4) Трансформації типу логарифм, квадратний корінь, піднесення у степінь тощо. Приклади таких перетворень наведені у фрагменті коду нижче. Для виконання багатьох перетворень зручніше за все використовувати функцію mutate() з пакету dplyr. Її першим аргументом є таблиця даних, яка містить необхідні змінні:</p>
<p>Фрагмент коду 6. Основні трансформації змінних</p>
<pre><code>## Перевертання шкали, Сумарний бал, Категоризація неперервної змінної
library(dplyr)
pss &lt;- mutate(
  pss, 
  b4 = 4 - b4, b5 = 4 - b5, 
  b7 = 4 - b7, b8 = 4 - b8,
  score1 = b1 + b2 + b3 + b6 + b9 + b10,
  score2 = b4 + b5 + b7 + b8,
  score = score1 + score2,
  group = cut(score, breaks = 4, include.lowest = TRUE)
)

# Створення змінної через перекодування існуючої
library(car)
pss$fin &lt;- recode(
  pss$fin_state, as.factor = TRUE,
  recodes = "1:2 = 'A'; 3 = 'B'; 4:5 = 'C'"
)</code></pre>
<p>Всі інші аргументи, вказані через кому, визначають ті трансформації, які необхідно здійснити з існуючими змінними, наприклад: 1) для змінних b4, b5, b7, b8 перевертається шкала (це питання із зворотним ключем); 2) обчислюються три інтегральні показники score1 і score2 як сума балів за прямі і зворотні питання шкали PSS, а потім утворюється змінна score як їхня сума; 3) Змінна score розбивається на чотири рівних діапазони (категоризується) функцією cut().</p>
<p>У другій частині наведеного фрагменту відбувається перекодування категоріальної змінної fin_state (фінансовий стан сім’ї досліджуваного) за допомогою функції recode() з пакету car. Її п’ять значень перекодовуються у три категорії A, B і C, оскільки наповненість першої і п’ятої категорій («Не вистачає грошей на їжу» та «Можемо купувати все, що захочемо») є недостатньою. Аргументу recodes передається рядок, в якому вказується схема перекодування існуючих значень у нові. Створений фактор fin з трьома рівнями буде використаний пізніше при проведенні дисперсійного аналізу.</p>
<p>Таблиці і графіки розподілу (гістограми, боксплоти), а також описові статистики дають можливість зрозуміти поведінку змінних, діагностувати незвичайні спостереження і прийняти рішення про необхідні перетворення. Функція descriptives() з пакету jmv корисна тим, що виводить основні описові статистики і графіки:</p>
<p>Фрагмент коду 7. Описові статистики</p>
<pre><code>library(jmv)
descriptives(
  data = pss, vars = c(score1, score2, score, b1, b2),
  skew = TRUE, sd = TRUE, kurt = TRUE, 
  hist = TRUE, freq = TRUE, box = TRUE 
)</code></pre>
<p>Порівняння середніх двох незалежних сукупностей. Після підготовки даних можна перейти до застосування статистичних критеріїв, призначених для перевірки гіпотез про існування відмінностей і зв’язків у популяції, що вивчається. Почнемо з порівняння двох незалежних груп ¬– чоловіків і жінок – за середнім значенням і дисперсією. Наступний блок містить виклик функції ttestIS(), яка виводить велику кількість корисної табличної і графічної інформації для такого порівняння:</p>
<p>Фрагмент коду 8. Замовлення t-критерію Ст’юдента для незалежних груп</p>
<pre><code>library(jmv)

ttestIS(
  formula = score ~ sex, data = pss,
  welchs = TRUE, mann = TRUE, hypothesis = "twoGreater",
  norm = TRUE, eqv = TRUE,
  effectSize = TRUE, ciES = TRUE,
  desc = TRUE, plots = TRUE
)</code></pre>
<p>Аргументу formula передається вираз, який містить символ ~ (тильда). Зліва від тильди вказано залежну неперервну змінну – сумарний бал score за шкалою стресу PSS. Після тильди йде незалежна дихотомічна змінна sex, за значеннями якої досліджувані потрапляють в одну з двох категорій за статтю. Додатково до t-критерію Ст’юдента для незалежних сукупностей функції замовляється обчислення критерію Уелча (аргумент welchs = TRUE), непараметричного критерію Манна-Уітні (аргумент mann = TRUE), величини ефекту d Коена і його довірчих інтервалів (аргументи effectSize = TRUE і ciES = TRUE), критерію Лівена для перевірки гіпотези про рівність дисперсій в двох сукупностях (аргумент eqv = TRUE), а також побудова таблиці з описовими статистиками і діаграми (аргументи desc = TRUE, plots = TRUE). Нарешті, аргумент hypothesis = “twoGreater” визначає тип альтернативної гіпотези: «у другій групі (тобто, у жінок) середнє значення є більшим у популяції».</p>
<p>Як можемо бачити у наступній таблиці, всі три критерія дають можливість відкинути нульову гіпотезу про відсутність відмінностей середніх значень суб’єктивного переживання стресу чоловіків і жінок у популяції студентів НаУКМА в 2019 році на рівні α = 0.001 й прийняти альтернативну гіпотезу: середнє значення для чоловіків є меншим, ніж у жінок.</p>
<p>Величина ефекту d дорівнює -0.427 (від’ємне значення з’явилося внаслідок того, що від меншого середнього віднімалося більше). За Дж. Коеном, це ефект майже середньої сили. Що важливіше, ми отримали не тільки точкову оцінку величини ефекту, але й 95-відсотковий довірчий інтервал, який несе інформацію про точність цієї оцінки: в популяції величина ефекту може знаходитися в проміжку від слабкого до посереднього:</p>
<p>Таблиця 3. Критерії для порівняння двох незалежних груп</p>
<pre><code>Independent Samples T-Test 
─────────────────────────────────────────────────────────────────────
                 Statistic   df    p      Cohen's d   Lower    Upper 
─────────────────────────────────────────────────────────────────────
 Student's t         -4.17   460   &lt; .001    -0.427   -0.633   -0.219
 Welch's t           -4.21   255   &lt; .001    -0.427   -0.633   -0.219
 Mann-Whitney U      16683         &lt; .001    -0.427   -0.633   -0.219
─────────────────────────────────────────────────────────────────────
Note. Hₐ Males &lt; Females</code></pre>
<p>Критерій Лівена для цих даних дорівнює 0.276 з ступенями свободи 1 і 460 (таблиця не наводиться за браком місця). Таке або ще більше значення критерію, коли нульова гіпотеза про рівність дисперсій в популяції є вірною, можна отримати з ймовірністю 0.600 (р-значення). Отже, на рівні статистичної значущості α = 0.05 ми не можемо відкинути нульову гіпотезу про рівність дисперсій на користь альтернативної. Нарешті, таблиця з описовими статистиками для чоловіків і жінок дозволяє зрозуміти, яким є значення стресу для типового представника (середнє і медіана), з якою точністю вдалося оцінити середнє значення у популяції на основі вибіркових даних (стандартна похибка середнього SE), наскільки варіативними є дані в кожній групі (стандартне відхилення SD).</p>
<p>Таблиця 4. Описові статистики по групах</p>
<pre><code>Group Descriptives                                              
 ─────────────────────────────────────────────────────────────── 
            Group       N      Mean    Median    SD      SE      
 ─────────────────────────────────────────────────────────────── 
   score    Чоловіки    135    19.5      19.0    7.26    0.625   
            Жінки       327    22.6      23.0    7.41    0.410   
 ───────────────────────────────────────────────────────────────</code></pre>
<p>На основі цих описових статистик будується графік з довірчими інтервалами навколо середніх значень, який більш наочно передає знайдені відмінності у рівні суб’єктивного стресу (не наводиться за браком місця).</p>
<p>Порівняння середніх більше ніж двох незалежних сукупностей. Якщо кількість груп, які порівнюються за середнім значенням, дві чи більше, дослідник може використати однофакторний дисперсійний аналіз для перевірки альтернативної гіпотези про те, що відмінності існують на рівні популяцій. На сьогоднішній день в методологічній літературі існує думка, що найкращим показником величини ефекту в цьому випадку є ω^2, а не η^2 – звичний показник частки поясненої дисперсії залежної змінної у вибірці, яка є зміщеною оцінкою поясненої дисперсії у популяції.</p>
<p>Продемонструю використання однофакторного дисперсійного аналізу на прикладі даних про стрес. Нехай залежною змінною виступить score, сумарний бал по шкалі суб’єктивного стресу PSS, а незалежною – категоріальна змінна (фактор) fin, фінансовий стан сім’ї студента після перекодування. Фактор fin має три рівні після перекодування змінної fin_state: А – не вистачає грошей на їжу або вистачає на їжу, але одяг купувати вже складно, В – доводиться економити, щоб купити коштовні речі, С – можуть купувати деякі коштовні речі або можуть купувати все, що хочуть. Оскільки нестача фінансових ресурсів може виступати однією з прямих чи опосередкованих причин стресу, варто перевірити гіпотезу про існування відмінностей у сприйнятті стресу студентами в залежності від потрапляння в категорію А, В чи С. Для проведення аналізу скористаємося функцією ANOVA() з пакету jmv:</p>
<p>Таблиця 5. Виклик однофакторного дисперсійного аналізу</p>
<pre><code>library(jmv)
ANOVA(
  formula = score ~ fin, data = pss,
  effectSize = "omega", homo = TRUE, norm = TRUE, 
  postHoc = ~ fin, postHocCorr = "scheffe", 
  emMeans = ~ fin, emmTables = TRUE
)</code></pre>
<p>Аргументи formula і data грають ту саму роль, що й у прикладі з t-критерієм Ст’юдента, аргументу effectSize передається назва показника величини ефекту, аргументи postHoc і postHocCorr визначають, за якою змінною проводиться попарний аналіз різниці середніх та метод корекції статистичної значущості при множинних порівняннях. Аргументи homo і norm замовляють перевірку припущень про однорідність дисперсій і нормальність розподілу залежної змінної, важливі умови для застосування дисперсійного аналізу. Нарешті, аргументи emMeans і emmTables замовляють виведення таблиці і графіку з описовими статистиками по групах. Наведу лише дві таблиці з великої кількості результатів, які генерує ця функція:</p>
<p>Таблиця 6. Таблиця дисперсійного аналізу і величина ефекту</p>
<pre><code>ANOVA - score                                                       
─────────────────────────────────────────────────────────────────── 
           Sum of Squares   df   Mean Square   F      p       ω²    
─────────────────────────────────────────────────────────────────── 
fin                   808     2        403.8   7.38   &lt; .001  0.027 
Residuals           25103   459         54.7                        
─────────────────────────────────────────────────────────────────── </code></pre>
<p>Отже, F критерій виявився статистично значущим на рівні 0.001, а величина ефекту вказує на слабку залежність. Оскільки критерії Лівена і Шапіро-Уілка виявилися статистично незначущими (тобто, дані не суперечать припущенням про те, що залежна змінна має нормальний розподіл і її дисперсія однакова в трьох групах), ми можемо використовувати F критерій для висновку про рівність середніх.</p>
<p>Зверніть увагу, що ми отримали лише точкову оцінку величини ефекту, отже, потрібні додаткові дії для побудови довірчого інтервалу. Скористаємося функцією omega.F() з пакету MOTE. Значення для її аргументів візьмемо з таблиці дисперсійного аналізу, яка була наведена вище:</p>
<p>Фрагмент коду 9. Визначення довірчих інтервалів для величини ефекту ω²</p>
<pre><code>library(MOTE)
result &lt;- omega.F(dfm = 2, dfe = 459, Fvalue = 7.383, n = 462, a = 0.05)
unlist(result[1:3])</code></pre>
<p>Отримані результати подаються в публікації у наступному вигляді: ω^2=.027, 95% CI [0.004, 0.061]. Отже, ми отримали слабкий ефект, який в популяції всіх студентів НаУКМА 2019 року може насправді знаходитися у діапазоні від тривіально малого до посереднього. Для точнішої оцінки знадобиться більша вибірка. Зазвичай після того, як дослідник приймає загальну альтернативну гіпотезу про існування відмінностей середніх між якимись групами, цілком логічним є поставити питання: які саме групи відрізняються (Post Hoc латиною означає «після того, як»)? Наступна таблиця містить результати всіх попарних порівнянь груп:</p>
<p>Таблиця 7. Попарні порівняння середніх значень</p>
<pre><code>Post Hoc Comparisons - fin                                    
───────────────────────────────────────────────────────────── 
fin     fin   Mean Difference   SE      df    t     p-tukey   
───────────────────────────────────────────────────────────── 
A   -   B                3.99   1.462   459   2.73    0.018   
    -   C                5.28   1.427   459   3.70   &lt; .001   
B   -   C                1.28   0.725   459   1.77    0.181   
─────────────────────────────────────────────────────────────</code></pre>
<p>Отже, лише найбідніші досліджувані статистично значущо відрізняються від представників двох інших категорій, різниця середніх за показником суб’єктивного стресу оцінюється в 3.99 і 5.38 балів за шкалою PSS відповідно.</p>
<p>Кореляційний аналіз. У вітчизняній психології кореляційні дослідження зустрічаються значно частіше за експериментальні, тому у більшості публікацій наводяться результати парного кореляційного аналізу. Оскільки коефіцієнт кореляції вже є показником величини ефекту, для врахування сучасних методологічних вимог нам потрібно частіше: 1) Планувати об’єм вибірки у відповідності до очікуваної сили зв’язку; 2) Наводити в публікаціях довірчі інтервали для коефіцієнтів кореляції; 3) Використовувати корекцію на множинні порівняння при проведенні пошукових досліджень. Ось приклад того, як кореляційний аналіз можна провести в R за допомогою функції corr.test() з пакету psych:</p>
<p>Фрагмент коду 10. Кореляційний аналіз</p>
<pre><code>library(psych)
cm &lt;- corr.test(x = pss[2:5], method = "pearson", adjust = "hochberg")
print(cm, digits = 3, short = FALSE)</code></pre>
<p>Першим аргументом функції є таблиця даних. В квадратних дужках після імені таблиці можна вказати вектор номерів або імен змінних, які беруть участь в кореляційному аналізі – в даному прикладі це змінні у стовпчиках з другого по п’ятий. Аргумент method вказує функції, який саме з трьох коефіцієнтів кореляції має бути обчислений: Пірсона, Спірмена чи Кендала. Аргументу adjust передають назву метода корекції статистичної значущості з врахуванням кількості змінних (в даному прикладі це сучасний метод Хохберга). Для виведення довірчих інтервалів результати кореляційного аналізу, записані в об’єкті cm, мають друкуватися з опцією short = FALSE). Поглянемо на те, як між собою пов’язані перші чотири питання з шкали PSS:</p>
<p>Таблиця 8. Кореляційна матриця</p>
<pre><code>Correlation matrix 
      b1    b2    b3    b4
b1 1.000 0.434 0.415 0.248
b2 0.434 1.000 0.471 0.406
b3 0.415 0.471 1.000 0.368
b4 0.248 0.406 0.368 1.000</code></pre>
<p>Як можна бачити, сила лінійного зв’язку між індикаторами шкали PSS коливається від середньої (b1 і b4) до сильної (b2 і b3). При змістовній інтерпретації кореляцій слід враховувати те, що сильний зв’язок може бути наслідком схожості питань.</p>
<p>В наступній таблиці міститься матриця р-значень, на основі яких дослідник приймає рішення про те, яку з двох гіпотез слід обрати: нульову – в популяції коефіцієнт кореляції в точності дорівнює нулю, чи альтернативну – в популяції кореляція відрізняється від нульової. При цьому значення вище діагоналі скориговані на кількість здійснених перевірок. Оскільки всі елементи в цій частині матриці наближаються до нуля, кореляційні коефіцієнти залишилися статистично значущими, навіть не зважаючи на корекцію:</p>
<p>Таблиця 9. Статистична значущість коефіцієнтів кореляції</p>
<pre><code>Probability values 
(Entries above the diagonal are adjusted for multiple tests.) 
   b1 b2 b3 b4
b1  0  0  0  0
b2  0  0  0  0
b3  0  0  0  0
b4  0  0  0  0</code></pre>
<p>Нарешті, в останній таблиці містяться 95-відсоткові довірчі інтервали для коефіцієнтів кореляції змінних у популяції. Так, оцінка сили зв’язку питань b1 і b2 в популяції перебуває у діапазоні від 0.357 (посередній ефект) до 0.505 (сильний ефект). Отже, довірчий інтервал є достатньо широким, незважаючи на велику вибірку. Таке подання дозволяє іншим дослідникам розуміти, з якою точністю вдалося оцінити величину ефекту у конкретному дослідженні.</p>
<p>Таблиця 10. Довірчі інтервали для коефіцієнтів кореляції Пірсона</p>
<pre><code>      raw.lower raw.r raw.upper 
b1-b2     0.357 0.434     0.505 
b1-b3     0.336 0.415     0.488 
b1-b4     0.160 0.248     0.332 </code></pre>
<p>Зв’язок категоріальних змінних. Застосування коефіцієнтів кореляції Пірсона до змінних, виміряних у п’ятибальній шкалі, суперечить припущенням, які лежать в основі цієї статистики: метрична шкала вимірювання змінних, лінійність зв’язку і двовимірний нормальний розподіл. Більш коректним і інформативним підходом в цьому випадку є побудова таблиці сполучення (contingency table) і вивчення нелінійного зв’язку в ній. Побудувати таку таблицю в R можна, наприклад, за допомогою функції contTables() з пакету jmv:</p>
<p>Фрагмент коду 11. Побудова таблиці сполучення</p>
<pre><code>library(jmv)
contTables(
  rows = b3, cols = sex, data = pss, 
  phiCra = TRUE, taub = TRUE, pcCol = TRUE
)</code></pre>
<p>Аргументи функції вказують, які змінні відповідають рядкам (rows) і стовпчикам таблиці (cols), чи слід обчислювати показник сили зв’язку φ та V Крамера (phiCra) і виводити відсотки, обчислені по стовпчиках таблиці (pcCol).</p>
<p>Як показав такий аналіз, найтісніший зв’язок між статтю досліджуваного і індикаторами шкали суб’єктивного стресу існує для третього питання: «Як часто протягом останнього місяця ви відчували себе знервованим чи в стані стресу?» . Наприклад, відповідь з кодом 4 – «Дуже часто» – дають 32.6% чоловіків (біля третини) і 46.8% жінок (біля половини). Статистика χ² (хі-квадрат) має значення 24.7 при чотирьох ступенях свободи, що є статистично значущим показником на рівні α = 0.001 і дозволяє відкинути нульову гіпотезу про те, категоріальні змінні не пов’язані в популяції студентів НаУКМА в 2019 році.</p>
<p>Таблиця 11. Таблиця сполучення і критерій χ²</p>
<pre><code>Contingency Tables                                        
 ───────────────────────────────────────────────────────── 
   b3                       Чоловіки      Жінки    Total   
 ───────────────────────────────────────────────────────── 
   0        % within column      5.2        0.6      1.9   
   1        % within column     16.3        6.4      9.3   
   2        % within column     22.2       16.8     18.4   
   3        % within column     23.7       29.4     27.7   
   4        % within column     32.6       46.8     42.6   
   Total    % within column    100.0      100.0    100.0   
 ─────────────────────────────────────────────────────────

 χ² Tests                        
 ─────────────────────────────── 
         Value    df    p        
 ─────────────────────────────── 
   χ²     27.4     4    &lt; .001   
   N       462                   
 ───────────────────────────────</code></pre>
<p>Висновку про наявність статистично значущого зв’язку замало для сучасного дослідження, тому за допомогою функції v.chi.sq() з пакету MOTE ми можемо побудувати довірчий інтервал для V Крамера – міри сили зв’язку номінальних категоріальних змінних. Для її аргументів візьмемо інформацію з вищенаведених таблиць:</p>
<p>Фрагмент коду 12. Побудова довірчих інтервалів для V Крамера і w Коена</p>
<pre><code>library(MOTE)  
v &lt;- v.chi.sq(x2 = 27.404, n = 462, r = 5, c = 2)
unlist(v[1:3])

# w Коена
unlist(v[1:3]) * sqrt(2 - 1)</code></pre>
<p>В результаті отримаємо такі статистики: V = .24, 95% CI [.14, .26] та χ^2(8) = 27.40, p &lt; .001 (подання у стилі АПА). Завдяки простому перетворенню з V також можна отримати значення показника w Коена: w = 0.24, 95% CI [.16, .34]. Отже, мова тут йде про зв’язок середньої сили, який в популяції може виявитися і слабким.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./intro.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Вступ</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./summary.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Висновки</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>